website/blog/urls.py
from blog import views
from django.urls import path,re_path
from django.conf.urls import url,include
from django.views.generic.base import RedirectView

urlpatterns = [
   re_path(r'^$',views.index,name='index'),#博客首页
   re_path(r'^(?P<blog_id>[0-9]+)$',views.detail,name='detail'),#每一页博客
   re_path(r'^category/(?P<category_id>[0-9]+)$',views.category,name='category'),#分类博客
   re_path(r'^tag/(?P<tag_id>[0-9]+)$',views.tag,name='tag'),#标签博客
   re_path(r'^search/$',views.search,name='search'),#搜索博客
   re_path(r'^archives/(?P<year>[0-9]+)/(?P<month>[0-9]+)$',views.archives,name='archives'),#博客归档
   re_path(r'^login$',views.login,name='login'),#登陆
   re_path(r'^register/$',views.register,name='register'),#注册
   re_path(r'^register_handle$',views.register_handle,name='register_handle'),#注册验证
   re_path(r'^login_active$',views.login_active,name='login_active'),#登陆验证
   re_path(r'^active/(?P<token>.*)$', views.Active, name='active'),  # 用户激活
   re_path(r'^logout$',views.Logout,name='logout'),#退出登陆
   re_path(r'^reply/(?P<comment_id>\d+)/$', views.reply, name='comment_reply'),#评论
   re_path(r'^myblog$',views.My_blog,name='myblog'),#我的博客
   re_path(r'^favicon\.ico$',RedirectView.as_view(url=r'static/blog/images/favicon.ico')),#小图标
   re_path(r'^myimages$',views.myimages,name='myimages'),#我的图片
   re_path(r'^update/$',views.register_form,name='update'),#注册
   re_path(r'^download/(?P<file_id>[0-9]+)$',views.File_Download,name='download'),#文件下载
   re_path(r'^file/$',views.File_Show,name='fileShow')#文件列表
]

website/website/urls.py
from django.contrib import admin
from django.urls import path,re_path
from django.conf.urls import url,include
from django.conf import settings
from django.conf.urls.static import static
from blog.feed import LatestEntriesFeed
from blog import views as vw
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from blog.models import Entry
from blog.views import register_handle
info_dict={
    'queryset':Entry.objects.all(),
    'date_field':'modified_time',
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/',include('tinymce.urls')),
    path('latest/feed/',LatestEntriesFeed()),
    # path('login/',include('blog.urls','blog'),namespace='login'),
    # path('register/',include('blog.urls','blog'),namespace='register'),
    path('comments/',include('django_comments.urls')),
    path('',include(('blog.urls','blog'),namespace='blog')),
    path(r'sitemap/.xml',sitemap,{'sitemaps':{'blog':GenericSitemap(info_dict=info_dict,priority=0.6)}}),#站点目录

]+static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
#static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
# static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

handler404=vw.Not_page_found_404
handler403=vw.Not_page_found_403
handler500=vw.Page_error_500

website/blog/models.py
from django.db import models
# from django.contrib.auth.models import User
from tinymce.models import HTMLField
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    '''用户模型类'''
    create_time = models.DateField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateField(auto_now=True, verbose_name='更新时间')
    is_detele = models.BooleanField(default=False, verbose_name='删除标记')
    class Meta:
        db_table='df_user'
        verbose_name='用户'#这个生成的是“用户s”
        verbose_name_plural=verbose_name#这个可以将后面s去掉

#导航分类
class Category(models.Model):
    name=models.CharField(max_length=128,verbose_name='博客分类')
    def __str__(self):#返回对象的名称
        return self.name
    class Meta:#返回表的名称
        verbose_name='博客分类'
        verbose_name_plural='博客分类'

#标签
class Tag(models.Model):
    name=models.CharField(max_length=128,verbose_name='博客标签')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name='博客标签'
        verbose_name_plural='博客标签'

#文章
class Entry(models.Model):
    # user = models.ForeignKey('User', verbose_name='作者', on_delete=models.CASCADE)
    title=models.CharField(max_length=128,verbose_name='博客标题')
    user=models.ForeignKey('User',verbose_name='博客作者',on_delete=models.CASCADE)
    img=models.ImageField(upload_to='blog_images',null=True,blank=True,verbose_name='博客图片')
    body = models.TextField(verbose_name='博客正文')
    abstract=models.TextField(max_length=256,null=True,blank=True,verbose_name='博客摘要')
    visiting=models.PositiveIntegerField(default=0,verbose_name='博客访问量')
    category=models.ManyToManyField('Category',verbose_name='博客分类')
    tag=models.ManyToManyField('Tag',verbose_name='博客标签')
    created_time=models.DateTimeField(auto_now_add=True,verbose_name='创建时间')
    modified_time=models.DateTimeField(auto_now=True,verbose_name='更新时间')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'blog_id': self.id})  # http://127.0.0.1/blog/3

    # def  get_absolute_url(self):
    #     return

#访问量增加
    def increase_visiting(self):
        self.visiting+=1
        self.save(update_fields=['visiting'])

    class Meta:
        ordering=['-created_time']#排序
        verbose_name='博客'
        verbose_name_plural='博客'



#文件上传
class FileUpdate(models.Model):
    name=models.CharField(max_length=128,verbose_name='文件名称')
    update_time=models.DateTimeField(auto_now_add=True,verbose_name='提交时间')
    files = models.FileField(upload_to='blog_images',null=True,blank=True,verbose_name='博客文件')
    def __str__(self):#返回对象的名称
        return self.name
    class Meta:#返回表的名称
        verbose_name='博客文件'
        verbose_name_plural='博客文件'

website/blog/views.py
from django.shortcuts import render
from blog.models import Entry, Category, Tag
import markdown
from django import forms
from django.db.models import Q
from django.core.paginator import Paginator
import pygments
from django.shortcuts import get_object_or_404
from django_comments.models import Comment
from django_comments import models as comment_models

import re
from blog.models import User, FileUpdate
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponse
from itsdangerous import SignatureExpired
from django.contrib.auth import authenticate,logout
from django.contrib.auth import login as log
from utils.mixin import LoginRequiredMixin
# Create your views here.

# def make_paginator(objects, page, num=5):
#     paginator = Paginator(objects, num)
#     try:
#         object_list = paginator.page(page)
#     except PageNotAnInteger:
#         object_list = paginator.page(1)
#     except EmptyPage:
#         object_list = paginator.page(paginator.num_pages)
#     return object_list, paginator


# def pagination_data(paginator, page):
#     """
#     用于自定义展示分页页码的方法
#     :param paginator: Paginator类的对象
#     :param page: 当前请求的页码
#     :return: 一个包含所有页码和符号的字典
#     """
#     if paginator.num_pages == 1:
#         # 如果无法分页，也就是只有1页不到的内容，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
#         return {}
#     # 当前页左边连续的页码号，初始值为空
#     left = []
#
#     # 当前页右边连续的页码号，初始值为空
#     right = []
#
#     # 标示第 1 页页码后是否需要显示省略号
#     left_has_more = False
#
#     # 标示最后一页页码前是否需要显示省略号
#     right_has_more = False
#
#     # 标示是否需要显示第 1 页的页码号。
#     # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
#     # 其它情况下第一页的页码是始终需要显示的。
#     # 初始值为 False
#     first = False
#
#     # 标示是否需要显示最后一页的页码号。
#     # 需要此指示变量的理由和上面相同。
#     last = False
#
#     # 获得用户当前请求的页码号
#     try:
#         page_number = int(page)
#     except ValueError:
#         page_number = 1
#     except:
#         page_number = 1
#
#     # 获得分页后的总页数
#     total_pages = paginator.num_pages
#
#     # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
#     page_range = paginator.page_range
#
#     if page_number == 1:
#         # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
#         # 此时只要获取当前页右边的连续页码号，
#         # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
#         # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
#         right = page_range[page_number:page_number + 4]
#
#         # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
#         # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
#         if right[-1] < total_pages - 1:
#             right_has_more = True
#
#         # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
#         # 所以需要显示最后一页的页码号，通过 last 来指示
#         if right[-1] < total_pages:
#             last = True
#
#     elif page_number == total_pages:
#         # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
#         # 此时只要获取当前页左边的连续页码号。
#         # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
#         # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
#         left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
#
#         # 如果最左边的页码号比第 2 页页码号还大，
#         # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
#         if left[0] > 2:
#             left_has_more = True
#
#         # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
#         # 所以需要显示第一页的页码号，通过 first 来指示
#         if left[0] > 1:
#             first = True
#     else:
#         # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
#         # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
#         left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
#         right = page_range[page_number:page_number + 2]
#
#         # 是否需要显示最后一页和最后一页前的省略号
#         if right[-1] < total_pages - 1:
#             right_has_more = True
#         if right[-1] < total_pages:
#             last = True
#
#         # 是否需要显示第 1 页和第 1 页后的省略号
#         if left[0] > 2:
#             left_has_more = True
#         if left[0] > 1:
#             first = True
#
#     data = {
#         'left': left,
#         'right': right,
#         'left_has_more': left_has_more,
#         'right_has_more': right_has_more,
#         'first': first,
#         'last': last,
#     }
#     return data

def login(request):
    """登陆"""
    if 'username' in request.COOKIES:  # 如果用户前次登陆勾选记住用户名
        username = request.COOKIES.get('username')
        checked = 'checked'
    else:
        username = ''
        checked = ''
    return render(request, 'blog/login.html', {'username': username, 'checked': checked})

def Logout(request):
    """注销"""
    logout(request)
    return redirect(reverse('blog:index'))


def register(request):
    """注册"""

    return render(request,'blog/register.html',locals())



def register_handle(request):
    '''用户注册验证'''
    #获取注册信息
    username=request.POST.get('user_name')
    password=request.POST.get('pwd')
    cpassword=request.POST.get('cpwd')
    email=request.POST.get('email')
    allow=request.POST.get('allow')

    #进行用户信息校验 all方法就是用来判断3个信息是否一致，都一致为真返回true，否之，false
    if not all([username,password,email]):
        return render(request,'blog/register.html',{'errmsg':'数据不完整'})
    
    #用户密码校验
    if password !=cpassword:
        return render(request,'blog/register.html',{'errmsg':'前后输入密码不一致'})

    if len(password)<=6:
        return render(request,'blog/register.html',{'errmsg':'用户密码最少6位'})

    if len(password)>=12:
        return render(request,'blog/register.html',{'errmsg':'用户密码最多12位'})


    #主要就是用来校验邮箱是否合法，
    if not re.match(r'^[a-z0-9][\w.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$',email):
        return render(request,'blog/register.html',{'errmsg':'邮箱不合法'})

    #校验用户是否勾选同意协议
    if allow!='on':
        return render(request,'blog/register.html',{'errmsg':'请勾选协议'})
#判断注册用户是否以存在，如果不存在就值为空，因为如果查找不到回抛出异常
    try:
        user = User.objects.get(username=username)
    except User.DoesNotExist:
        user=None
    if user:
        return render(request,'blog/register.html',{'errmsg':'用户名已存在'})

    #将注册信息添加到数据库表中
    user=User.objects.create_user(username,email,password)
    # user=User()
    # user.username=username
    # user.password=password
    # user.email=email
    # #将用户激活状态值为0，因为我们创建默认是激活的
    user.is_active=0
    user.save()
    #用户邮箱发送激活验证，验证通过就激活，根据唯一标识id来判断是哪个用户
    #发送的，对用户的id进行加密，防止发生安全隐患
    serializer=Serializer(settings.SECRET_KEY,3600)#加密方式，加密时间
    info={'confirm':user.id}#获取用户id
    token=serializer.dumps(info)#对用户id进行加密
    token=token.decode()#默认加密后是byte类型，解密为utf8
    #发送邮件
    subject='懿曼博客给你一封邮件'#邮件主题
    message=''#邮件内容
    sendir=settings.EMAIL_FROM#发送方
    receiver=[email]
    html_message='<h1>%s,懿曼博客欢迎你到来</h1>请点击以下链接进行激活<br/><a href="http://www.yiman.info/active/%s">点击我进行激活</a>'%(username,token)
    send_mail(subject=subject,message=message,from_email=sendir,recipient_list=receiver,html_message=html_message)

    #防止url逆向，
    return redirect(reverse('blog:index'))

def Active(request,token):
    """激活用户"""
    #对用户信息进行解密
    serializer=Serializer(settings.SECRET_KEY,3600)
    try:
        info=serializer.loads(token)
        user_id=info['confirm']#获取解密id
        user=User.objects.get(id=user_id)#获取用户信息
        user.is_active=1#激活
        user.save()
        #跳转到登陆页面
        return redirect(reverse('blog:login'))
    except SignatureExpired as e:
        return HttpResponse('对不起，激活时间过期')

def login_active(request):
    """登陆验证"""
    username = request.POST.get('username')
    password = request.POST.get('pwd')
    remember = request.POST.get('remember')
    # 判断用户数据的完整性
    if not all([username, password]):
        return render(request, 'blog/login.html', {'errmsg': '请输入登陆账号或者密码'})
    # 判断用户信息是否正确，这里我们使用django默认的认证系统，可以对我们加密的用户密码进行解码
    user = authenticate(username=username, password=password)

    if user is not None:
        # 表示用户信息正确
        if user.is_active:
            # 记录用户的登陆状态，如果用户已经激活 login是django默认的
            log(request, user)
            # 获取登陆后要跳转的地址 next对应的值就是要跳转的下一个地址，如果没有那个地址了，默认跳到主页
            next_url = request.GET.get('next', reverse('blog:index'))
            response = redirect(next_url)
            if remember == 'on':  # 如果勾选记住用户名
                response.set_cookie('username', username, max_age=20)
            else:
                response.delete_cookie(username)
            # 跳转到首页
            return response

        else:  # 用户没有激活
            return render(request, 'blog/login.html', {'errmsg': '你好你的账户未激活'})

    else:  # 用户信息不正确
        return render(request, 'blog/login.html', {'errmsg': '密码或者账号不正确'})
#import pysnooper
#@pysnooper.snoop()
def index(request):
    """首页"""
    entries = Entry.objects.all().order_by('-id')
    # print(entries)
    # page = request.GET.get('page')
    # print(page)
    # paginator = Paginator(entries, 2)
    # try:
    #     int(page)
    # except Exception as e:
    #     page = 1
    # if int(page) > paginator.num_pages:
    #     page = 1
    # entry_list = paginator.page(page)  # 获取当前页面的所有商品
    # number_pages = paginator.num_pages  # 获取总页数
    # if number_pages <= 5:
    #     pages = range(1, number_pages + 1)
    # elif int(page) <= 3:
    #     pages = range(1, 6)
    # elif number_pages - int(page) <= 2:
    #     pages = range(number_pages - 4, number_pages + 1)
    # else:
    #     pages = range(int(page) - 2, int(page) + 3)
    #
    # print(pages)
    #
    # content = {'entries': entries,
    #            'pages': pages,
    #            'entry_list': entry_list}

    return render(request, 'blog/index.html', locals())


# def index(request):
#     entries = Entry.objects.all()
#     page = request.GET.get('page', 1)
#     entry_list, paginator = make_paginator(entries, page)
#     page_data = pagination_data(paginator, page)
#
#     return render(request, 'blog/index.html', locals())

def detail(request, blog_id):
    """详情页"""

website/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}基础模板{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'blog/css/blog_nav.css' %}" rel="stylesheet">
    {% block css %}

    {% endblock %}
    <!-- HTML5 shim 和 Respond.js 是为了让 IE8 支持 HTML5 元素和媒体查询（media queries）功能 -->
    <!-- 警告：通过 file:// 协议（就是直接将 html 页面拖拽到浏览器中）访问页面时 Respond.js 不起作用 -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

  <nav class="navbar navbar-fixed-top">

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        {# 品牌名 #}
        <a class="navbar-brand" href="{% url 'blog:myblog' %}"><img src="{% static 'blog/images/logo_test.jpeg' %}"><span class="navbar-text">我的博客</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="my-nav">
      <ul class="nav navbar-nav">

        <li class="active"><a href="/">博客</a></li>
        <li ><a href="{% url 'blog:myblog' %}">关于博主</a></li>
        <li ><a href="{% url 'blog:myblog' %}">联系我们</a></li>

      </ul>
      <form class="navbar-form navbar-left" action="/search/" method="get">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="keyword">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>
       <ul class="nav navbar-nav navbar-right">
              {% if user.is_authenticated %}
                  欢迎你:<em>{{ user.username }}</em>
                  <a href="{% url 'blog:logout' %}">退出</a>
              {% else %}

                  <a href="{% url 'blog:login' %}">登陆</a>
                  <a href="{% url 'blog:register' %}">注册</a>

              {% endif %}
          </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->

</nav>
{#   <video id="v1" autoplay loop muted>#}
{#              <source src="{% static 'blog/images/blog_video2.mp4' %}" type="video/mp4"  />#}
{#        </video>#}
        <h4 style="color:black">  {% block content %}{% endblock %}</h4>


    <div id="back-to-top">
        <i class="glyphicon glyphicon-arrow-up"></i>
    </div>

   <footer>
    <div class="footer" role="navigation">
        <div class="container">
            <div class="navbar-text">
                <ul class="footer-text">
                    <li><a href="{% url 'blog:index' %}">主页</a></li>
                    <li><a href="{% url 'blog:myblog' %}">联系我们</a></li>
                    <li><a href="{% url 'blog:myimages' %}">博主联想</a></li>
                    <li><a href="">其他</a></li>
                     <li><a href="http://www.mylady.top/" style="color:blue" target="_black">友军网址:mylady的博客</a></li>
                </ul>
                <p>Copyright © 2020  懿曼的博客</p>
            </div>
        </div>
    </div>
</footer>

    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="{% static 'jquery-3.2.1.min.js' %}"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
       <script>
            $("#back-to-top").click(function () {
                window.scrollTo(0,0);
            });
        </script>
  {% block script %}

      {% endblock %}
  </body>
</html>

website/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load comments %}
{% block title %}博客第{{ blog_id }}页{% endblock %}
{% block css %}<link href="{% static 'blog/css/github.css'%}" rel="stylesheet">
               <link href="{% static 'blog/css/blog_nav.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <h2>{{ entry.title }}</h2>
                <p>
                    <strong>作者:{{ entry.user }}</strong>
                    &nbsp; &nbsp; &nbsp; &nbsp;发表时间：{{ entry.created_time }}

                    &nbsp; &nbsp; &nbsp; &nbsp;分类：
                    {% for categroy in entry.category.all %}
                        <a href="{% url 'blog:category' categroy.id %}">{{ categroy.name }}</a>
                    {% endfor %}

                    &nbsp; &nbsp; &nbsp; &nbsp;标签：
                    {% for tag in entry.tag.all %}
                        <a href="{% url 'blog:tag' tag.id %}">{{ tag.name }}</a>
                    {% endfor %}

                    &nbsp; &nbsp; &nbsp; &nbsp;浏览量：{{ entry.visiting }}
                </p>
                {% if entry.img %}
                    <div><img src="{{ entry.img.url }}" alt="博客图片" width="42%"></div>
                {% endif %}
                <hr/>
                {{ entry.toc|safe }}
                <p>{{ entry.body|safe }}</p>

                {# 评论 #}
                <div class="row">
                    <hr />
                    {% get_comment_form for entry as form %}
                    {% get_comment_count for entry  as comment_count %}
                    <h3>评论总数： {{ comment_count }}</h3>
                <hr />
                </div>
                {#  评论表单#}
            {% if user.is_authenticated  %}
                <div class="row">
                    <form class="form-horizontal" action="{% comment_form_target %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="input_title" class="pull-left control-label">评论标题：</label>
                            <div class="col-sm-6">
                                <input class="form-control" name="comment_title" id="input_title" placeholder="请输入标题" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="input_comment" class="pull-left control-label">评论内容:</label>
                            <div class="col-sm-6">
                            <textarea style="resize:none;" class="form-control" rows=6 name="comment" id="input_comment" placeholder="在此输入评论" required></textarea>
                            </div>
                        </div>
                        <span style="display: none;">{{ form.honeypot }}</span>
                        {{ form.content_type }}
                        {{ form.object_pk }}
                        {{ form.timestamp }}
                        {{ form.security_hash }}
                        <input type="hidden" name="next" value="{% url 'blog:detail' entry.id %}" />
                        <input  name="parent_id" type="hidden" value="-1" />
                        <input  name="level" type="hidden" value="0" />

                        <div class="form-group col-sm-7">
                            <div class="pull-left" style="margin-left: 68px;">
                                <button type="reset"  class="btn btn-default"><span class="glyphicon glyphicon-repeat"></span>&nbsp;&nbsp;重置</button>
                            </div>
                            <div class="pull-right" style="margin-right: 12px;">
                                <button type="submit" class="btn btn-success" id="id_submit"><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;评论</button>
                            </div>
                        </div>


                    </form>
                </div>
            {% else %}
                <h3>登陆后才可以评论</h3>
            {% endif %}
            <hr />

            {#            评论显示区#}
            <div class="row">
            {% for comment in comments %}

                    <div class="col-md-11 comment-content" style="margin-bottom: 10px;">
                        <strong>用户：{{ comment.name }}</strong>
                        <div>
                            <em>于{{ comment.submit_date }}对你的博客发表评论：</em>
                        </div>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ comment.comment }}</p>
                            {% if user.is_authenticated %}
                                &nbsp;&nbsp;<div class="button_style">&nbsp;<a href="{% url 'blog:comment_reply' comment.id %}">回复</a></div>
                            {% endif %}
                    </div>

            {% endfor %}
            </div>
            </div>

              <div class="col-md-3">
                 {% include 'blog/right_site.html' %}
              </div>
    </div>
        </div>
    </div>
{% endblock %}

website/blog/templates/blog/file_download.html
{% extends 'blog/base.html' %}

{% block title %}博客文件下载{% endblock %}
{% block content %}
    <table>
{% for file in file_objs %}
    <li><a href="{% url 'blog:download' file.id %}">{{ file.name }}
    </a></li>
{% endfor %}
    </table>
{% endblock %}

website/blog/templates/blog/upload_file.html
{% extends 'blog/base.html' %}

{% block title %}博客文件下载{% endblock %}
{% block content %}
 <h1>register</h1>
 <form method="post" enctype="multipart/form-data" >
 {% csrf_token %}
 {{uf.as_ul}}
 <input type="submit" value="ok" />
 </form>
{% endblock %}